=pod

=head1 NAME

xde-applets - package of 'C' language system tray and dock applets for XDE

=head1 DESCRIPTION

Provides a set of system tray and dock applets for use with an Arch
Linux based system.  The system tray icons dock apps provided in this
package are as follows:

=over

=item L<xde-av-applet(1)>

Provides a system tray and dock applet for monitoring DDNS and DNS-SD
networks.

=item L<xde-bt-applet(1)>

Provides a system tray and dock applet for managing and connecting
bluetooth devices to a computer.

=item L<xde-dh-applet(1)>

Provides a system tray and dock applet for managing and establishing
connections with the DHCP client daemon (L<dhcpcd(8)>).

=item L<xde-hal-applet(1)>

Provides a system tray and dock applet for monitoring HAL (which in turn
monitors devices and system resources).

=item L<xde-lm-applet(1)>

Provides a system tray and dock applet for monitoring LM sensor output.

=item L<xde-pk-applet(1)>

Provides a system tray and dock applet for monitoring and maintaining
ArchLinux packages.

=item L<xde-sd-applet(1)>

Provides a system tray and dock applet for monitoring L<systemd(1)>
activities.

=item L<xde-up-applet(1)>

Provides a system tray and dock applet for monitoring L<upower(1)>
levels and events.

=item L<xde-wl-applet(1)>

Provide a system tray and dock applet for managing and forming wireless
network connections using L<wpa_supplicant(1)>.

=back

=head1 CAVEATS

Not all of the programs of the original separate perl packages have
been converted successfully to C<C>.

=head1 HISTORY

Many of the tools in the B<xde-applets> package were originally written
as perl programs in separate packages.  One of the problems with
using perl for various things X is that perl has no support for various
libraries such as ICE, X11 session management and startup notification.
These libraries are useful things for a desktop environment.  Therefore,
each of the applets in the separate packages were converted from
perl programs to C<C> language programs.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

=head1 SEE ALSO

L<xde-av-applet(1)>,
L<xde-av-applet(1)>,
L<xde-bt-applet(1)>,
L<xde-dh-applet(1)>,
L<xde-hal-applet(1)>,
L<xde-lm-applet(1)>,
L<xde-pk-applet(1)>,
L<xde-sd-applet(1)>,
L<xde-up-applet(1)>,
L<xde-wl-applet(1)>,
L<wpa_supplicant(1)>,
L<dhcpcd(1)>

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
