=pod

=head1 NAME

 xde-au-applet - an Avahi system tray applet

=head1 SYNOPSIS

B< xde-au-applet> [ I<OPTIONS> ]
 B<xde-au-applet> --quit [ I<OPTIONS> ]
 B<xde-au-applet> --replace [ I<OPTIONS> ]
 B<xde-au-applet> --help [ I<OPTIONS> ]
 B<xde-au-applet> --version
 B<xde-au-applet> --copying

=head1 DESCRIPTION

B<xde-au-applet> is a system tray and dock application applet that
monitors and controls the desktop audio system.  Currently, it only
supports control and monitoring of the audio system using ALSA (Advanced
Linux Sound Architecture) and Pulse audio.

As a system-tray and dock-application applet, B<xde-au-applet> provides
a status icon and tool-tip pop-up controls for determining current audio
settings and providing for control of volume, muting and output
selection.

=head1 ARGUMENTS

None.

=head1 OPTIONS

The following options are accepted:

=head2 COMMAND OPTIONS

When specified, the following options alter the primary operating mode
of the program:

=over

=item [B<--monitor>, B<-m>]

When no command is specified, the default is to run the applet without
replacing an existing instance.  It is an error if an instance is
currently running.

=item B<--replace>, B<-r>

Run the applet, but replace a running instance of the applet.  It is not
an error when no instance is currently running.

=item B<--restart>, B<-S>

Ask a running instance to restart.  It is an error if there is no
instance currently running.  This is useful when the binary has been
upgraded.

=item B<--quit>, B<-q>

Ask a running instance of the applet to quit.  It is not an error if no
instance is currently running.

=item B<--help>, B<-h>

Prints usage information and the current options settings and defaults,
then exits.

=item B<--version>, B<-V>

Prints the version of the program and a brief copyright statement, then
exits.  Parse the first line with L<awk(1)> to obtain just the version
number.

=item B<--copying>, B<-C>

Prints the long copying permission statement, then exits.

=back

=head2 GENERAL OPTIONS

The following options are general options:

=over

=item B<--display>, B<-d> I<DISPLAY>

Specify the display to use (overriding the B<DISPLAY> environment
variable).  The default is the value of the B<DISPLAY> environment
variable.

=item B<--screen>, B<-s> I<SCREEN>

Specify the screen number to use when locating the current window and
workspace.  The default is either specified by the B<DISPLAY>
environment variable (when that variable specifies a screen); otherwise,
all screens will be considered by default.

=item B<--notray>, B<-Y> or B<--tray>, B<-y>

Specifies to install (B<-y>) or not to install (B<-Y>) a system tray
status icon.  The default is normally to install a system tray status
icon.  This option has no effect if a system tray is not running.

=item B<--nodock>, B<-K> or B<--dock>, B<-k>

Specifies to install (B<-k>) or not to install (B<-K>) a withdrawn
windowmaker dock application.  The default is dependent on the
B<XDG_CURRENT_DESKTOP> and detection of the running window manager.
This detection is performed to determine whether the desktop environment
and window manager is capable of handling a withdrawn windowmaker dock
application.  The default is to run a dock application if the desktop
environment or window manager supports it.  Specifying this option
overrides the default behaviour.

=back

=head2 SESSION MANAGEMENT OPTIONS

X session management options are not used by another user other than the
X11 Session Manager.  The following options are used by X session
management:

=over

=item B<-clientId> I<CLIENTID>

Specifies the X Session Management client identifier of the previously
running session of B<xde-au-applet>.

=item B<-restore> I<SAVEFILE>

Specifies the X Session Management filename of a file to which to save
session information.

=back

=head1 USAGE

=head1 BEHAVIOR

=head1 SOUNDS

B<xde-au-applet> plays the following sounds under the following
circumstances (see L<sound(7)>):

=over

=back

=head1 FILES

=head1 ENVIRONMENT

B<xde-au-applet> examines the following environment variables:

=over

=item B<USER>

Use to find the user's username.

=item B<HOME>

Used to find the user's home directory.

=item B<DISPLAY>

Used to determine the display on which to run.

=item B<SESSION_MANAGER>

Used to locate a connection to the X11R6 session manager.

=back

=head1 HISTORY

I wrote B<xde-au-applet> due to the deficiencies and lack of
availability of system tray and window-maker dock application
audio management and monitoring.
The program was originally written in C<perl,> but later ported to C<C>.

The L<pavucontrol(1)> applet is an excellent applet; however, it is a bit overkill and does not
provide very usable tool-tip pop-ups.  Although it can control all aspects of pulse audio,
something as simple a muting the microphone somehow escapes it.  It also
lacks hot-key and special function key capabilities.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

=head1 SEE ALSO

L<xde-applets(5)>.

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:

